{{- if .Values.cluster.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ include "kafka.ns" . }}
spec:
  kafka:
    version: 3.7.0
    replicas: {{ .Values.cluster.replicas }}
    listeners:
      {{- toYaml .Values.listeners | nindent 6 }}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: false
      log.message.timestamp.type: CreateTime
    storage:
      type: {{ .Values.cluster.storage.type }}
      volumes:
        {{- range .Values.cluster.storage.volumes }}
        - id: {{ .id }}
          type: persistent-claim
          size: {{ .size }}
          class: {{ .class }}
        {{- end }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas | default .Values.cluster.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size | default .Values.cluster.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class | default .Values.cluster.zookeeper.storage.class }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}

