{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels: {{- toYaml .Values.prometheus.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.prometheus.serviceMonitor.portName }}
      path: {{ .Values.prometheus.serviceMonitor.path }}
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
{{- end }}

